-- =============================================================================
-- Oracle schema — converted from SQL Server (db.sql)
-- Chi tiết từng bước: xem HUONG_DAN_ORACLE.md trong repo.
--
-- Image gvenzl/oracle-free: PDB = FREEPDB1, SYS dùng ORACLE_PASSWORD.
-- Image Oracle XE: thường PDB = XEPDB1 (đổi JDBC + lệnh sqlplus cho khớp).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Bảng tra cứu (không phụ thuộc FK)
-- ---------------------------------------------------------------------------
CREATE TABLE ChatLieu (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE ChucVu (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE DanhMucSP (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE KichCo (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE MauSac (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE NSX (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE ThuongHieu (
    Id  NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50)   NOT NULL
);

CREATE TABLE KhuyenMai (
    Id           NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten          NVARCHAR2(50)   NOT NULL,
    Ngaybatdau   DATE            NOT NULL,
    Ngayketthuc  DATE            NOT NULL,
    HinhthucKM   NVARCHAR2(50)   NOT NULL,
    Giatrigiam   NUMBER(18,0)    DEFAULT 0,
    Trangthai    NUMBER(1)       DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Chi tiết sản phẩm
-- ---------------------------------------------------------------------------
CREATE TABLE ChitietSP (
    Id           NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ma           NVARCHAR2(10)   NOT NULL,
    Ten          NVARCHAR2(50)   NOT NULL,
    IdNsx        NUMBER(10),
    IdMauSac     NUMBER(10),
    IdDMuc       NUMBER(10),
    IdKC         NUMBER(10),
    IdCL         NUMBER(10),
    IdTH         NUMBER(10),
    IdKM         NUMBER(10),
    MoTa         NVARCHAR2(50)   DEFAULT NULL,
    SoLuongTon   NUMBER(10),
    GiaNhap      NUMBER(20,0)    DEFAULT 0,
    GiaBan       NUMBER(20,0)    DEFAULT 0,
    QrCode       VARCHAR2(4000)  DEFAULT NULL,
    CONSTRAINT FK_CTSP_CHATLIEU   FOREIGN KEY (IdCL)     REFERENCES ChatLieu (Id),
    CONSTRAINT FK_CTSP_DANHMUC    FOREIGN KEY (IdDMuc) REFERENCES DanhMucSP (Id),
    CONSTRAINT FK_CTSP_KICHCO     FOREIGN KEY (IdKC)     REFERENCES KichCo (Id),
    CONSTRAINT FK_CTSP_KM         FOREIGN KEY (IdKM)     REFERENCES KhuyenMai (Id),
    CONSTRAINT FK_CTSP_MAUSAC     FOREIGN KEY (IdMauSac) REFERENCES MauSac (Id),
    CONSTRAINT FK_CTSP_NSX        FOREIGN KEY (IdNsx)    REFERENCES NSX (Id),
    CONSTRAINT FK_CTSP_THUONGHIEU FOREIGN KEY (IdTH)     REFERENCES ThuongHieu (Id)
);

-- ---------------------------------------------------------------------------
-- Người dùng / nhân viên (tên bảng Users — Oracle lưu dạng USERS, JDBC khớp)
-- ---------------------------------------------------------------------------
CREATE TABLE Users (
    Id         NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten        NVARCHAR2(30)   NOT NULL,
    TenDem     NVARCHAR2(30)   DEFAULT NULL,
    Ho         NVARCHAR2(30)   DEFAULT NULL,
    NgaySinh   DATE            DEFAULT NULL,
    Gioitinh   NUMBER(1),
    Sdt        VARCHAR2(30)    DEFAULT NULL,
    IdCV       NUMBER(10),
    TaiKhoan   VARCHAR2(50)    DEFAULT NULL,
    MatKhau    VARCHAR2(255)   DEFAULT NULL,
    Email      VARCHAR2(255)   NOT NULL,
    TrangThai  NUMBER(1)       DEFAULT 0,
    CONSTRAINT FK_USERS_CHUCVU FOREIGN KEY (IdCV) REFERENCES ChucVu (Id)
);

CREATE TABLE KhachHang (
    Id          NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten         NVARCHAR2(30)   NOT NULL,
    TenDem      NVARCHAR2(30)   DEFAULT NULL,
    Ho          NVARCHAR2(30)   DEFAULT NULL,
    Gioitinh    NUMBER(1),
    NgaySinh    DATE            DEFAULT NULL,
    Email       VARCHAR2(255)   NOT NULL,
    Sdt         VARCHAR2(30)    DEFAULT NULL,
    Diemthuong  NUMBER(10)      DEFAULT NULL
);

CREATE TABLE HoaDon (
    Id              NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdKH            NUMBER(10),
    IdNV            NUMBER(10),
    Ma              VARCHAR2(20),
    NgayTao         TIMESTAMP(6)    DEFAULT NULL,
    NgayThanhToan   DATE            DEFAULT NULL,
    TinhTrang       NUMBER(1)       DEFAULT 0,
    Ghichu          VARCHAR2(255),
    TongTien        NUMBER(18,0),
    CONSTRAINT UQ_HOADON_MA UNIQUE (Ma),
    CONSTRAINT FK_HD_KH   FOREIGN KEY (IdKH) REFERENCES KhachHang (Id),
    CONSTRAINT FK_HD_NV   FOREIGN KEY (IdNV) REFERENCES Users (Id)
);

CREATE TABLE HoaDonChiTiet (
    IdHD     NUMBER(10)    NOT NULL,
    IdCTSP   NUMBER(10)    NOT NULL,
    Soluong  NUMBER(10)    NOT NULL,
    Dongia   NUMBER(18,0) NOT NULL,
    CONSTRAINT PK_HDCT PRIMARY KEY (IdHD, IdCTSP),
    CONSTRAINT FK_HDCT_HD   FOREIGN KEY (IdHD)   REFERENCES HoaDon (Id),
    CONSTRAINT FK_HDCT_CTSP FOREIGN KEY (IdCTSP) REFERENCES ChitietSP (Id)
);

COMMIT;
